#!bin/sh
# allure 环境变量

environment="GITLAB_USER_NAME=$GITLAB_USER_NAME
\nCI_COMMIT_AUTHOR=$CI_COMMIT_AUTHOR
\nCI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA
\nCI_COMMIT_TITLE=$CI_COMMIT_TITLE
\nCI_COMMIT_BRANCH=$CI_COMMIT_BRANCH
\nCI_PROJECT_NAME=$CI_PROJECT_NAME
\nCI_PROJECT_URL=$CI_PROJECT_URL
"

if [ $REPOSITORY_NAME ];then
  $environment=$REPOSITORY_NAME + '\n' + $environment
fi

echo $environment